name: contributors

on:
  push:
    branches:
      - main

jobs:
  contributor_list:
    runs-on: ${{ matrix.os  }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: cjdenio/contributor_list@master
        with:
          commit_message: 'Documentation: update contributors list'
          max_contributors: 5


